service:
  port: :8080
  debug: true
database:
  admin:
    type: mysql
    dsn: root:123456@tcp(192.168.5.132:3306)/ruoyi?charset=utf8mb4&parseTime=True&loc=Local
    prefix: ry_ # 表前缀
    max-idle: 10 # 连接池最大闲置的连接数
    max-open: 10 # 连接池最大打开的连接数
    max-lifetime: 30 #连接对象可重复使用的时间长度(秒)
    debug: true # 是否开启 sql 调试模式